### ISSUE TITLE
TicTacToe wiki page.

### ISSUE THREAD

**Issue by karacasoft** [cagatayyildiz/cmpe160#1]
Kullanımıyla alakalı kısa bir bilgilendirme iş görür sanırım.

**Comment by cagatayyildiz** [comment]
Done.

**Comment by karacasoft** [comment]
Wiki page hala boş :V https://github.com/cagatayyildiz/cmpe160/wiki/TicTacToe 

Ama konu kapandı diyorsak saygılar.

**Comment by cagatayyildiz** [comment]
README'yi update etmiştim, wiki'ye de yapıştırdım şimdi
